# Generated by Django 3.1 on 2020-12-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('vip_expire_date', models.DateField(default=None, null=True, verbose_name='Expire Date')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Is Trial')),
                ('available_days', models.PositiveIntegerField(default=0, verbose_name='Available Days')),
                ('apple_auto_renew', models.BooleanField(default=False, verbose_name='Apple Is Auto Renew Subscription')),
                ('vip_order', models.JSONField(default=dict, verbose_name='Vip Orders')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='用户')),
                ('age', models.IntegerField(default=28, verbose_name='年龄')),
            ],
            options={
                'verbose_name': 'UserInfo',
                'verbose_name_plural': 'UserInfo',
            },
        ),
    ]
